#include <curl/curl.h>

int scalanative_CURL_GLOBAL_ALL = CURL_GLOBAL_ALL;
int scalanative_CURLMSG_DONE = CURLMSG_DONE;
int scalanative_CURLMOPT_SOCKETFUNCTION = CURLMOPT_SOCKETFUNCTION;
int scalanative_CURLMOPT_TIMERFUNCTION = CURLMOPT_TIMERFUNCTION;
int scalanative_CURLOPT_PRIVATE = CURLOPT_PRIVATE;
int scalanative_CURLINFO_PRIVATE = CURLINFO_PRIVATE;
int scalanative_CURLINFO_RESPONSE_CODE = CURLINFO_RESPONSE_CODE;
int scalanative_CURLOPT_URL = CURLOPT_URL;
int scalanative_CURLOPT_WRITEDATA = CURLOPT_WRITEDATA;
int scalanative_CURLOPT_WRITEFUNCTION = CURLOPT_WRITEFUNCTION;
int scalanative_CURL_SOCKET_TIMEOUT = CURL_SOCKET_TIMEOUT;
int scalanative_CURL_POLL_IN = CURL_POLL_IN;
int scalanative_CURL_POLL_OUT = CURL_POLL_OUT;
int scalanative_CURL_POLL_INOUT = CURL_POLL_INOUT;
int scalanative_CURL_POLL_REMOVE = CURL_POLL_REMOVE;
int scalanative_CURL_CSELECT_IN = CURL_CSELECT_IN;
int scalanative_CURL_CSELECT_OUT = CURL_CSELECT_OUT;
