name: ci

on:
  push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Mill cache
      uses: actions/cache@v2
      with:
        path: ~/.mill
        key: mill-${{ hashFiles('.mill-version') }}
    - name: Ivy cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/coursier
        key: ivy-${{ hashFiles('build.sc') }}
        restore-keys: |
          ivy-${{ hashFiles('build.sc') }}
          ivy
    - name: Compilation cache
      uses: actions/cache@v2
      with:
        path: ./out
        key: out
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libuv1-dev libcurl4-openssl-dev
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
        architecture: x64
    - name: Update
      run: 
        ./mill --no-server --disable-ticker __.resolvedIvyDeps
        # ./mill -j 0 mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll --sources buildSources
    - name: Check formatting
      run: 
        ./mill --no-server --disable-ticker -j 0 mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll __.sources
        # ./mill -j 0 mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll --sources buildSources
    - name: Compile
      run: 
        ./mill --no-server --disable-ticker -j 0 __.compile
    - name: Test
      run:
        ./mill --no-server --disable-ticker -j 0 __.test
  publish-sonatype:
    if: github.repository == 'lolgab/scala-native-http-client-async' && contains(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-20.04
    env:
      SONATYPE_PGP_PRIVATE_KEY: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY }}
      SONATYPE_PGP_PRIVATE_KEY_PASSWORD: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY_PASSWORD }}
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v2
      - name: Mill cache
        uses: actions/cache@v2
        with:
          path: ~/.mill
          key: mill-${{ hashFiles('.mill-version') }}
      - name: Ivy cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: ivy-${{ hashFiles('build.sc') }}
          restore-keys: |
            ivy-${{ hashFiles('build.sc') }}
            ivy
      - name: Compilation cache
        uses: actions/cache@v2
        with:
          path: ./out
          key: out
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          architecture: x64
      - name: Publish to Maven Central
        run: |
          if [[ $(git tag --points-at HEAD) != '' ]]; then
            echo $SONATYPE_PGP_PRIVATE_KEY | base64 --decode > gpg_key
            gpg --import --no-tty --batch --yes gpg_key
            rm gpg_key
            ./mill -i --disable-ticker mill.scalalib.PublishModule/publishAll \
              --sonatypeCreds $SONATYPE_USER:$SONATYPE_PASSWORD \
              --gpgArgs --passphrase=$SONATYPE_PGP_PRIVATE_KEY_PASSWORD,--no-tty,--pinentry-mode,loopback,--batch,--yes,-a,-b \
              --publishArtifacts __.publishArtifacts \
              --readTimeout 600000 \
              --awaitTimeout 600000 \
              --release true \
              --signed true
          fi
